#!/bin/bash

CPATH=.
CPATH=$CPATH:lib/log4j-1.2.13.jar
CPATH=$CPATH:lib/antlr-3.2.jar
CPATH=$CPATH:build/classes

# To set the page-size to use:
# JAVA_OPTS="-Dlog4j.configuration=logging.conf -Dnanodb.pagesize=2048"

JAVA_OPTS="-Dlog4j.configuration=logging.conf"

java $JAVA_OPTS -cp $CPATH edu.caltech.nanodb.client.ExclusiveClient

